// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtyService.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace DowntownRealty {
  public static partial class DowntownRealty
  {
    static readonly string __ServiceName = "DowntownRealty";

    static readonly grpc::Marshaller<global::DowntownRealty.RealtyRequest> __Marshaller_RealtyRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DowntownRealty.RealtyRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DowntownRealty.RealtyResponse> __Marshaller_RealtyResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DowntownRealty.RealtyResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DowntownRealty.RealtyListRequest> __Marshaller_RealtyListRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DowntownRealty.RealtyListRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DowntownRealty.RealtyListResponse> __Marshaller_RealtyListResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DowntownRealty.RealtyListResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DowntownRealty.UserRequest> __Marshaller_UserRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DowntownRealty.UserRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DowntownRealty.UserResponse> __Marshaller_UserResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DowntownRealty.UserResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::DowntownRealty.RealtyRequest, global::DowntownRealty.RealtyResponse> __Method_GetRealtyById = new grpc::Method<global::DowntownRealty.RealtyRequest, global::DowntownRealty.RealtyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRealtyById",
        __Marshaller_RealtyRequest,
        __Marshaller_RealtyResponse);

    static readonly grpc::Method<global::DowntownRealty.RealtyListRequest, global::DowntownRealty.RealtyListResponse> __Method_GetRealtyList = new grpc::Method<global::DowntownRealty.RealtyListRequest, global::DowntownRealty.RealtyListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRealtyList",
        __Marshaller_RealtyListRequest,
        __Marshaller_RealtyListResponse);

    static readonly grpc::Method<global::DowntownRealty.UserRequest, global::DowntownRealty.UserResponse> __Method_GetUserById = new grpc::Method<global::DowntownRealty.UserRequest, global::DowntownRealty.UserResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUserById",
        __Marshaller_UserRequest,
        __Marshaller_UserResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DowntownRealty.RealtyServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DowntownRealty</summary>
    public abstract partial class DowntownRealtyBase
    {
      public virtual global::System.Threading.Tasks.Task<global::DowntownRealty.RealtyResponse> GetRealtyById(global::DowntownRealty.RealtyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::DowntownRealty.RealtyListResponse> GetRealtyList(global::DowntownRealty.RealtyListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::DowntownRealty.UserResponse> GetUserById(global::DowntownRealty.UserRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(DowntownRealtyBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetRealtyById, serviceImpl.GetRealtyById)
          .AddMethod(__Method_GetRealtyList, serviceImpl.GetRealtyList)
          .AddMethod(__Method_GetUserById, serviceImpl.GetUserById).Build();
    }

  }
}
#endregion
