// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Dictionary {
  public static partial class DictionaryService
  {
    static readonly string __ServiceName = "DictionaryService";

    static readonly grpc::Marshaller<global::Dictionary.DictionaryRequest> __Marshaller_DictionaryRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dictionary.DictionaryRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dictionary.DictionaryResponse> __Marshaller_DictionaryResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dictionary.DictionaryResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Dictionary.DictionaryRequest, global::Dictionary.DictionaryResponse> __Method_GetByNames = new grpc::Method<global::Dictionary.DictionaryRequest, global::Dictionary.DictionaryResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetByNames",
        __Marshaller_DictionaryRequest,
        __Marshaller_DictionaryResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dictionary.ServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DictionaryService</summary>
    public abstract partial class DictionaryServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Dictionary.DictionaryResponse> GetByNames(global::Dictionary.DictionaryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(DictionaryServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetByNames, serviceImpl.GetByNames).Build();
    }

  }
}
#endregion
