// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtyService.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace DowntownRealty {
  public static partial class DowntownRealty
  {
    static readonly string __ServiceName = "DowntownRealty";

    static readonly grpc::Marshaller<global::DowntownRealty.EmptyRequest> __Marshaller_EmptyRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DowntownRealty.EmptyRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DowntownRealty.EmptyResponse> __Marshaller_EmptyResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DowntownRealty.EmptyResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DowntownRealty.RealtyRequest> __Marshaller_RealtyRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DowntownRealty.RealtyRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DowntownRealty.RealtyResponse> __Marshaller_RealtyResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DowntownRealty.RealtyResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DowntownRealty.RealtyListRequest> __Marshaller_RealtyListRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DowntownRealty.RealtyListRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DowntownRealty.RealtyListResponse> __Marshaller_RealtyListResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DowntownRealty.RealtyListResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DowntownRealty.UserRequest> __Marshaller_UserRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DowntownRealty.UserRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DowntownRealty.UserResponse> __Marshaller_UserResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DowntownRealty.UserResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::DowntownRealty.EmptyRequest, global::DowntownRealty.EmptyResponse> __Method_HellowWorld = new grpc::Method<global::DowntownRealty.EmptyRequest, global::DowntownRealty.EmptyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "HellowWorld",
        __Marshaller_EmptyRequest,
        __Marshaller_EmptyResponse);

    static readonly grpc::Method<global::DowntownRealty.RealtyRequest, global::DowntownRealty.RealtyResponse> __Method_GetRealtyById = new grpc::Method<global::DowntownRealty.RealtyRequest, global::DowntownRealty.RealtyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRealtyById",
        __Marshaller_RealtyRequest,
        __Marshaller_RealtyResponse);

    static readonly grpc::Method<global::DowntownRealty.RealtyListRequest, global::DowntownRealty.RealtyListResponse> __Method_GetRealtyList = new grpc::Method<global::DowntownRealty.RealtyListRequest, global::DowntownRealty.RealtyListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRealtyList",
        __Marshaller_RealtyListRequest,
        __Marshaller_RealtyListResponse);

    static readonly grpc::Method<global::DowntownRealty.UserRequest, global::DowntownRealty.UserResponse> __Method_GetUserById = new grpc::Method<global::DowntownRealty.UserRequest, global::DowntownRealty.UserResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUserById",
        __Marshaller_UserRequest,
        __Marshaller_UserResponse);

    static readonly grpc::Method<global::DowntownRealty.UserRequest, global::DowntownRealty.UserResponse> __Method_UserExchange = new grpc::Method<global::DowntownRealty.UserRequest, global::DowntownRealty.UserResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "UserExchange",
        __Marshaller_UserRequest,
        __Marshaller_UserResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DowntownRealty.RealtyServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for DowntownRealty</summary>
    public partial class DowntownRealtyClient : grpc::ClientBase<DowntownRealtyClient>
    {
      /// <summary>Creates a new client for DowntownRealty</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public DowntownRealtyClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DowntownRealty that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public DowntownRealtyClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected DowntownRealtyClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected DowntownRealtyClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::DowntownRealty.EmptyResponse HellowWorld(global::DowntownRealty.EmptyRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return HellowWorld(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DowntownRealty.EmptyResponse HellowWorld(global::DowntownRealty.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_HellowWorld, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::DowntownRealty.EmptyResponse> HellowWorldAsync(global::DowntownRealty.EmptyRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return HellowWorldAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::DowntownRealty.EmptyResponse> HellowWorldAsync(global::DowntownRealty.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_HellowWorld, null, options, request);
      }
      public virtual global::DowntownRealty.RealtyResponse GetRealtyById(global::DowntownRealty.RealtyRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetRealtyById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DowntownRealty.RealtyResponse GetRealtyById(global::DowntownRealty.RealtyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRealtyById, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::DowntownRealty.RealtyResponse> GetRealtyByIdAsync(global::DowntownRealty.RealtyRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetRealtyByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::DowntownRealty.RealtyResponse> GetRealtyByIdAsync(global::DowntownRealty.RealtyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRealtyById, null, options, request);
      }
      public virtual global::DowntownRealty.RealtyListResponse GetRealtyList(global::DowntownRealty.RealtyListRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetRealtyList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DowntownRealty.RealtyListResponse GetRealtyList(global::DowntownRealty.RealtyListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRealtyList, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::DowntownRealty.RealtyListResponse> GetRealtyListAsync(global::DowntownRealty.RealtyListRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetRealtyListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::DowntownRealty.RealtyListResponse> GetRealtyListAsync(global::DowntownRealty.RealtyListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRealtyList, null, options, request);
      }
      public virtual global::DowntownRealty.UserResponse GetUserById(global::DowntownRealty.UserRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetUserById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DowntownRealty.UserResponse GetUserById(global::DowntownRealty.UserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUserById, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::DowntownRealty.UserResponse> GetUserByIdAsync(global::DowntownRealty.UserRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetUserByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::DowntownRealty.UserResponse> GetUserByIdAsync(global::DowntownRealty.UserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUserById, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::DowntownRealty.UserRequest, global::DowntownRealty.UserResponse> UserExchange(grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UserExchange(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::DowntownRealty.UserRequest, global::DowntownRealty.UserResponse> UserExchange(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_UserExchange, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override DowntownRealtyClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DowntownRealtyClient(configuration);
      }
    }

  }
}
#endregion
